### ISSUE TITLE
Add a Lint GitHub Action Workflow

### ISSUE THREAD

**Issue by coliff** [h5bp/main.css#143]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

It'd be neat to add a GitHub Action Lint workflow. I think we could use Super Linter (https://github.com/github/super-linter), maybe with the following config to start with.

```yml
name: Lint Code Base

on:
  push:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_MARKDOWN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
